### PR TITLE
Lab#1

### PR DESCRIPTION
**Pull request by SaranshPK**
@nchen269 @pjiang99 I finished lab 1,

### CODE REVIEW

**Comment by nchen269** [comment]
For the exponential distribution, you had line "print(f'Probability that measurement of 4 or greater is background: {pval:.4f}')"
Did you mean measurement of 3 or greater, since that's the hypothetical measurement you chose?

**Comment by SaranshPK** [comment]
Yeah I meant 3 or greater. Good catch,

**Comment by pjiang99** [comment]
For the charts you made for the binomial distributions, do you think it would be better to change them from bar charts to something like dots or vertical lines? I think this could probably show more clearly that these charts are PMFs instead of PDFs.

**Comment by SaranshPK** [comment]
I tried that and it looks like this:
image

I think that the data points makes it look like it could be continuous so I decided to use a bar graph.

**Comment by SaranshPK** [comment]
@kentwils My lab 1 report is complete.

**Pull request merged**
