### PR TITLE
Lab#3

### PR DESCRIPTION
**Pull request by SaranshPK**
@nchen269 @pjiang99 Lab 3 Draft Complete

### CODE REVIEW

**Comment by pjiang99** [comment]
Hi Saransh,

I see in Problem 3 you calculated the sum of the Poisson distributions numerically using numpy.convolve. I think this way is perfectly fine. But do you think it would be more accurate and efficient if you instead calculate the sum analytically using the fact that the sum of two Poisson distributions is still a Poisson?

**Comment by SaranshPK** [comment]
Yeah you're right. I changed the way I do the calculation.

**Comment by SaranshPK** [comment]
@kentwils Lab 3 Complete

**Comment by nchen269** [comment]
Hi Saransh, sorry for the late comment. It might help make the report even more clearer by including the questions too. Other than that it looks great!

**Pull request merged**
